const {chromium}=require('playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
const helper=fs.readFileSync('theme-picker-common.js','utf8');
const script=fs.readFileSync('manapool-theme-picker.user.js','utf8');
const cases=[
  {from:'2.13.0',stored:{palette:'navy',accent:'rose',intensity:'soft',fabTop:210},expect:{palette:'navy',accent:'rose',fabTop:210,shortcut:'Alt+G'}},
  {from:'3.0.2',stored:{settingsSchema:1,palette:'black',accent:'amber',intensity:'strong',fabTop:340,shortcut:'Alt+P'},expect:{palette:'black',accent:'amber',fabTop:340,shortcut:'Alt+P'}},
  {from:'3.0.7',stored:{settingsSchema:1,palette:'lightGray',accent:'green',intensity:'normal',fabTop:120,shortcut:'',updateNotifications:true},expect:{palette:'lightGray',accent:'green',fabTop:120,shortcut:'',updateNotifications:true}}
];
(async()=>{const browser=await chromium.launch({headless:true});try{for(const test of cases){const context=await browser.newContext({viewport:{width:1000,height:900}});await context.route('https://manapool.com/**',r=>r.fulfill({contentType:'text/html',body:'<main></main>'}));await context.route('https://api.github.com/**',r=>r.fulfill({status:404,body:''}));await context.addInitScript(values=>{for(const [k,v] of Object.entries(values))localStorage.setItem('gm-'+k,JSON.stringify(v));window.GM_getValue=(k,d)=>JSON.parse(localStorage.getItem('gm-'+k)||JSON.stringify(d));window.GM_setValue=(k,v)=>localStorage.setItem('gm-'+k,JSON.stringify(v));window.GM_registerMenuCommand=()=>{};},test.stored);await context.addInitScript({content:helper+'\n'+script});const page=await context.newPage();await page.goto('https://manapool.com/');const fab=page.locator('#theme-picker-fab');await fab.waitFor();const result=await page.evaluate(()=>({schema:JSON.parse(localStorage.getItem('gm-settingsSchema')),palette:JSON.parse(localStorage.getItem('gm-palette')),accent:JSON.parse(localStorage.getItem('gm-accent')),fabTop:JSON.parse(localStorage.getItem('gm-fabTop')),shortcut:JSON.parse(localStorage.getItem('gm-shortcut')),updateNotifications:JSON.parse(localStorage.getItem('gm-updateNotifications'))}));result.top=(await fab.boundingBox()).y;assert.equal(result.schema,1,`${test.from} schema`);for(const [key,value] of Object.entries(test.expect))assert.equal(result[key],value,`${test.from} ${key}`);assert(Math.abs(result.top-test.expect.fabTop)<2,`${test.from} dock position`);await context.close();}console.log('Theme Picker upgrade matrix OK');}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
